### ISSUE TITLE
JavaScript group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by J-C-S-V** [J-C-S-V/capstone-project-module-2#21]
Hello reviewer 👋,

We are 2 people on this project. @J-C-S-V  and @Danfall369 

## GitHub project.

https://github.com/J-C-S-V/capstone-project-module-2/projects/1

**Comment by Qoosim** [comment]
#  *Status: Required Changes* :recycle:

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Kanban board setup. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

- [x] It is required that every task should be assigned with a group member and their profile picture should appear on the task assigned to him or her. I could see that some tasks have no profile picture like others do. Kindly assign the remaining tasks to group members as you did for some.

### Your Kanban board
[board.webm](https://user-images.githubusercontent.com/26597432/232611164-28c7bf0d-3d20-43e8-9db4-809c8bee8be2.webm)
 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by J-C-S-V** [comment]
Hello @Qoosim!

Thank you for letting us know and for the video. We already fixed that.

Regards!
